[tool.commitizen]
name = "cz_conventional_commits"
version = "1.0.0"
version_files = [
    "pubspec.yaml:version",
]
tag_format = "$version"
annotated_tag = true
bump_message = "build(pubspec.yaml): increment version $current_version â†’ $new_version [skip-ci]"
update_changelog_on_bump = true

